### ISSUE TITLE
If there's a tie in the current numbers, adjust the chart labels.

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/yankee-derby#11]
None of this now
![screen shot 2018-04-12 at 3 42 15 pm](https://user-images.githubusercontent.com/125554/38700167-2763f792-3e68-11e8-9901-5034224fbc92.png)

**Comment by ssmirti** [comment]
If possible, in the event of a tied stat, can the text just be "tied". Obviously the overlap is not good, and it's possible that Stanton and Judge can also be the league leader in any of these categories.
![image uploaded from ios](https://user-images.githubusercontent.com/25779035/38741917-1fc8df2e-3f09-11e8-88ce-a9f12936af12.png)
