### ISSUE TITLE
The chart’s batting average y axis should have 3 decimal points and zero leading zeros

### ISSUE THREAD

**Issue by freejoe76** [nydailynews/yankee-derby#4]
per @ssmirti

**Comment by ssmirti** [comment]
The OPS y axis graph should also have 3 decimal points and not include 0. Should I open a new ticket for that?

**Comment by freejoe76** [comment]
@ssmirti the work on AVG is also being done for OPS, no need for a new ticket.

**Comment by freejoe76** [comment]
This is as done as it's going to get.
